version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "80:8096"
    volumes:
      - "jellyfin_config:/config"
      - "./media:/media"

  jellyfin_alexa_skill:
    image: ghcr.io/infinityofspace/jellyfin_alexa_skill:latest
    container_name: jellyfin-alexa-skill
    restart: unless-stopped
    depends_on:
      - jellyfin
      - skill_db
    ports:
      - "1456:1456"
    volumes:
      - "./skill.conf:/skill/config/skill.conf"
    healthcheck:
      test: ["CMD", "wget", "--spider", "--tries=1", "http://localhost:1456/healthy"]

  skill_db:
    image: 14.2-alpine3.15
    container_name: skill-db
    restart: unless-stopped
    volumes:
      - "skill_db_data:/var/lib/postgresql/data"

volumes:
  jellyfin_config:
    name: jellyfin_config
  skill_db_data:
    name: skill_db_data
